/*
 * ShapeTestPanel.java
 *
 * Created on August 23, 2006, 4:34 PM
 */

package org.jdesktop.swingx.painters;

import java.awt.Font;
import java.awt.Shape;
import java.util.HashMap;
import java.util.Map;
import org.jdesktop.swingx.JXPanel;
import org.jdesktop.swingx.JXPropertySheet2;
import org.jdesktop.swingx.combobox.MapComboBoxModel;
import org.jdesktop.swingx.painterset.*;
import org.jdesktop.swingx.util.ShapeUtils;

/**
 *
 * @author  joshy
 */
public class ShapeTestPanel extends javax.swing.JPanel {
    ShapeTest main;
    Map shapes;
    /** Creates new form ShapeTestPanel */
    public ShapeTestPanel() {
        initComponents();
        shapes = new HashMap();
        shapes.put("Triangle",ShapeUtils.generatePolygon(3,40,true));
        shapes.put("Hexagon",ShapeUtils.generatePolygon(6,40,true));
        shapes.put("Six Star",ShapeUtils.generatePolygon(6,40,20,true));
        shapes.put("Badge",ShapeUtils.generatePolygon(20,40,35,true));
        shapes.put("Square",ShapeUtils.generatePolygon(4,40,true));
        shapes.put("Letter S sans",PainterEditorPanel.stringToShape("S",new Font("Arial",Font.BOLD,160)));
        shapes.put("Letter S serif",PainterEditorPanel.stringToShape("S",new Font("Serif",Font.BOLD,160)));
        shapeSelector.setModel(new MapComboBoxModel(shapes));
    }
    public ShapeTestPanel(ShapeTest main) {
        this();
        this.main = main;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        preview = new JXPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sheet = new JXPropertySheet2(new Object());
        shapeSelector = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSplitPane1.setDividerLocation(200);
        preview.setToolTipText("asdf");
        org.jdesktop.layout.GroupLayout previewLayout = new org.jdesktop.layout.GroupLayout(preview);
        preview.setLayout(previewLayout);
        previewLayout.setHorizontalGroup(
            previewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 198, Short.MAX_VALUE)
        );
        previewLayout.setVerticalGroup(
            previewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 197, Short.MAX_VALUE)
        );
        jSplitPane1.setLeftComponent(preview);

        jScrollPane1.setToolTipText("asdf");
        sheet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(sheet);

        jSplitPane1.setRightComponent(jScrollPane1);

        shapeSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 4" }));
        shapeSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shapeSelectorActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Effect Enabled");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(shapeSelector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jCheckBox1)))
                        .addContainerGap())
                    .add(jButton1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(shapeSelector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCheckBox1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(main.isEffectEnabled()) {
            main.removeEffect();
        } else {
            main.addEffect();
        }
        preview.repaint();
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    
    private void shapeSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shapeSelectorActionPerformed
        main.sp.setShape((Shape) shapes.get(shapeSelector.getSelectedItem()));
        preview.repaint();
    }//GEN-LAST:event_shapeSelectorActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        preview.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    public javax.swing.JPanel preview;
    private javax.swing.JComboBox shapeSelector;
    public javax.swing.JTable sheet;
    // End of variables declaration//GEN-END:variables
    
}
